### ISSUE TITLE
Allow layers / volumes to use a noise texture for higher res mesh generation

### ISSUE THREAD

**Issue by Metapyziks** [Facepunch/sbox-sdf#2]
As suggested by @samzanemesis, this would let us keep the SDF low resolution and we'd invent detail when generating a mesh.

**Comment by samzanemesis** [comment]
Should be done by the brush itself really, I think the SDF texture has enough granularity to give some good texture to the mesh

eg 
![image](https://github.com/Facepunch/sbox-sdf/assets/6563447/7fa8a11c-aa5a-4f1d-84f8-0aff8ef7e347)
![image](https://github.com/Facepunch/sbox-sdf/assets/6563447/8111e491-0fc1-4637-8a27-520aab3e11ad)
