### ISSUE TITLE
`BaseNetworkable.OnCallRemoteProcedure` memory leak

### ISSUE THREAD

**Issue by PolSpock** [Facepunch/sbox-sdf#20]
Hello,

### Main topic

As i explained on this issue https://github.com/sboxgame/issues/issues/4109, i'm using the Facepunch [sbox-sdf](https://github.com/Facepunch/sbox-sdf) library for my game, and in the past, i used [sbox-csg](https://github.com/Facepunch/sbox-csg).

The common point between the 2 that i'm encountering ***** OUT OF MEMORY! /+/ attempted allocation size: 5000055 **** error on my sbox-server.exe running on windows dedicated server.

I've decided to investigate myself to spot the error, and i have spotted a crashing out of memory error caused by `BaseNetworkable.OnCallRemoteProcedure`

So here's the code i'm talking about: https://github.com/Facepunch/sbox-sdf/blob/main/libsdf/code/SdfWorld.Entity.cs#L114C32-L114C32

In fact, the more time passes by, the more you will increase your memory. And, arrived in a specific usage of memory, which I cannot explain how much and why, your server will run `***** OUT OF MEMORY! *****`

You can easily try the issue on my `sandbox` derived game: https://github.com/PolSpock/sbox-memory-leak/tree/main where you just have to spawn some [`OnCallRemoteProcedureEntity.cs`](https://github.com/PolSpock/sbox-memory-leak/blob/main/code/entities/OnCallRemoteProcedureEntity.cs) with the ingame Toolgun `code/tools/OnCallRemoteProcedureEntitySpawner.cs`

### What I've tried

So I've decided on a temporary solution to switch the SDF library `OnCallRemoteProcedure` usage to the more stable `INetworkSerializer` API.
Yes, the memory will still increase but it doesn't crash your server with of memory exception. And once again I cannot explain why.

However, since the SDF update for leaving the default Entity behavior, i haven't been able to [[Net] the `ISdfWorldImpl`](https://github.com/Facepunch/sbox-sdf/blob/3c0bd6040d0796d1bcb2ec541ede30279e23c6a4/libsdf/code/SdfWorld.cs#L136C1-L136C1)

I have tried so many Network shit on [SdfWorld.cs](https://github.com/Facepunch/sbox-sdf/blob/main/libsdf/code/SdfWorld.cs) but still unsuccessfully.

The only working behavior I have been able to do is to [Net] a Sdf2DWorld entity, but this creates some replication issues between Client/Server.
In fact, the client will not follow correctly some shared behaviour. For example, when i spawn it, it will create 2 separate entities both Server and Client, and when i delete one, only the serverside is deleted. Etc.

So if you could please bring me some answers i will be happy 🙏

Regards

**Comment by Metapyziks** [comment]
I should have time to look into this on Wednesday, thanks for reporting!

**Comment by Metapyziks** [comment]
Should be good now, but please give me a poke if you still have problems with it.

**Comment by PolSpock** [comment]
No server crashes anymore!
I am so happy, but at the same time, i feel so embarrassed that i couldn't find it myself 😳 some gaps in my knowledge of .NET 😅

**Comment by Metapyziks** [comment]
Your reproduction steps did 90% of the work for me, saving me so much time. I think you can be proud of that!
