### ISSUE TITLE
3D SDF UV's are broken

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-sdf#26]
I've tried to add uvs to a 3D sdf world, I've been told this is a bug by pol and its broken. I think this is only for 3D sdf, because 2d seems to work fine. I'm using a SDFVOL for the material. NOTE: I'm using this older version https://github.com/Facepunch/sbox-sdf/commit/85f29327a90ff8bd1eaf3b27ecbc9de8e2cef1ae of SDF since the latest builds don't work in sbox rn, my guess is because they were made on a branch @Metapyziks is working on 
![image](https://github.com/Facepunch/sbox-sdf/assets/95300917/bfbce61c-a653-4a30-b379-27c3e5bc95fe)

**Comment by Nolankicks** [comment]
I needed to use the shader.

**Comment by Metapyziks** [comment]
I've made it at least generate some UVs now, so you can use non-triplanar materials.

![](https://files.facepunch.com/ziks/2024-05-03/sbox-dev_pV7DEZpr1B.png)
