### ISSUE TITLE
"CallbackBatch.Add called outside batch for awake" error when joining an sdf world from a client

### ISSUE THREAD

**Issue by Nolankicks** [Facepunch/sbox-sdf#27]
When joining from another client, the SDF world has to regenerate on the second client and spits errors. 
Here's the link to the discord convo about it:https://discord.com/channels/833983068468936704/895597253316714497/1238311248710340720
![image](https://github.com/Facepunch/sbox-sdf/assets/95300917/9c92b80e-7e5e-420e-a61c-c0ce485896c4)
Repo:
`protected override void OnStart()
	{
		if (Networking.IsHost)
		{
			_ = Test();
		}
	}
	public async Task Test()
	{
		await World.AddAsync(new BoxSdf3D(Vector3.Zero, new Vector3(WorldSize, WorldSize, WorldHeight)), Grass);
		await OnWorldSpawned?.Invoke(this);
		await Task.Delay(1000);
		GameNetworkSystem.CreateLobby();
	}`

**Comment by Nolankicks** [comment]
I also get this error as well. Not sure if its related:
` 11:50:33   Generic  [1] Collection was modified; enumeration operation may not execute.`

**Comment by Metapyziks** [comment]
Pushed / published a possible fix.

**Comment by Nolankicks** [comment]
Yeah still getting this issue. The world is not spawned in when the player joins. Some things seem to be more stable though.
![image](https://github.com/Facepunch/sbox-sdf/assets/95300917/37c402da-0e41-4166-a1ea-450ab869273a)

**Comment by Metapyziks** [comment]
Investigating now.

**Comment by Metapyziks** [comment]
I haven't been able to repro this in my own project, I assume you're getting it in [sbox-OpenWorld](https://github.com/Nolankicks/sbox-OpenWorld)? Testing sdf_staging.scene I just get stuck on this:

![image](https://github.com/Facepunch/sbox-sdf/assets/1110904/9916dceb-828e-4027-819e-eb85abb2f79a)

How long should I wait?

**Comment by Metapyziks** [comment]
Closing because the original error is fixed, feel free to open another ticket if you're still getting the new error.
