### ISSUE TITLE
Rare System.Exception in scene!

### ISSUE THREAD

**Issue by ShadowBrian** [Facepunch/sbox-sdf#28]
![sbox-dev_0XYv7WTCri](https://github.com/Facepunch/sbox-sdf/assets/11138884/ce8a1703-b0c5-473c-a412-2677f55832a0)

![image](https://github.com/Facepunch/sbox-sdf/assets/11138884/a9c2299b-665d-4c1a-ba90-77f05e12e1e3)

**Comment by Metapyziks** [comment]
I think this is still #17, sorry for not sorting it out yet!
