### ISSUE TITLE
ClearAsync not clearing SdfWorld

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-sdf#29]
Trying to clear an Sdf2DWorld seems to be doing nothing. It seems to me that the clear code is running as expected, but there is no clearing happening.

**Comment by ShadowBrian** [comment]
As far as I can tell it's clearing the data but not updating the mesh to reflect it, and this is only apparent if you re-apply the same terrain data afterwards, leaving behind scorch marks and even chunks if you're making the terrain smaller, these chunks work fine again after loading a bigger map that encompasses them, it's a bit weird.

https://github.com/Facepunch/sbox-sdf/assets/11138884/acac08da-f9f9-41df-b602-994859cb9e56

This is me just clearing and re-applying the same terrain

**Comment by Metapyziks** [comment]
Pushed a possible fix.

**Comment by trundlr** [comment]
This seemed to be working now - thanks ziks! Btw if you could upload a new version of the lib with this change, that'd be great. I assume you were waiting to know if the fix worked. :)

**Comment by Metapyziks** [comment]
Thanks for testing, published!
